###############################################################################
## System Logger  https://www.home-assistant.io/components/logger
## levels: debug, fatal, critical, error, warning, warn, info, notset
###############################################################################
default: warn
logs: !include /config/logging/include/component_log_startup.yaml
filters:
  homeassistant.components.onvif:
    - 'Fetch snapshot image failed' #ERROR (MainThread) [homeassistant.components.onvif] Fetch snapshot image failed from LOREX-NVR, falling back to FFmpeg; Unknown error: Failed to authenticate to http://192.168.1.150/onvifsnapshot/media_service/snapshot?channel=4&subtype=1

  pybalboa.balboa:
    - 'Spa stopped responding, requesting panel config.' #ERROR (MainThread) [pybalboa.balboa] Spa stopped responding, requesting panel config.
    - 'Lost connection to spa, attempting reconnect' #ERROR (MainThread) [pybalboa.balboa] Lost connection to spa, attempting reconnect.
    - 'Error connecting to spa' #ERROR (MainThread) [pybalboa.balboa] Error connecting to spa at 192.168.1.125:4257: [Errno 110] Connect call failed ('192.168.1.125', 4257)
    - 'Connection reset by peer' #ERROR (MainThread) [pybalboa.balboa] Connection reset by peer
    - 'Message had bad CRC' #ERROR (MainThread) [pybalboa.balboa] Message had bad CRC, discarding
    - 'Spa unreachable' #ERROR (MainThread) [pybalboa.balboa] Spa unreachable
    - 'Spa sent an unknown message' #ERROR (MainThread) [pybalboa.balboa] Spa sent an unknown message: 7e17ffaf26008700000002000001000000000000000000087e
    - 'Spa read failed' #ERROR (MainThread) [pybalboa.balboa] Spa read failed: 0 bytes read on a total of 2 expected bytes

  homeassistant.components.balboa.const:
    - 'Failed to connect to spa' #ERROR (MainThread) [homeassistant.components.balboa.const] Failed to connect to spa at 192.168.1.125

  homeassistant.helpers.entity:
    - 'Update for sensor.chromecast_devices fails' #ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.chromecast_devices fails
    - 'is taking over 10 seconds' #WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.wan_connected is taking over 10 seconds
    - 'Update for sensor.waqi_windsor fails' #ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.waqi_windsor fails
    - 'Update for sensor.waqi_windsor_west_ontario_canada fails' #ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.waqi_windsor_west_ontario_canada fails
    - 'Update for sensor.waqi_windsor_downtown_ontario_canada fails' #ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.waqi_windsor_downtown_ontario_canada fails
    - 'Updating state for weather.weatherflow_local_hourly' #WARNING (MainThread) [homeassistant.helpers.entity] Updating state for weather.weatherflow_local_hourly (<class 'homeassistant.components.template.weather.WeatherTemplate'>) took 2.089 seconds. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+template%22
    - 'Updating state for weather.weatherflow_local_daily' #WARNING (MainThread) [homeassistant.helpers.entity] Updating state for weather.weatherflow_local_daily (<class 'homeassistant.components.template.weather.WeatherTemplate'>) took 1.752 seconds. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+template%22

  pychromecast.socket_client:
    - 'Heartbeat timeout, resetting connection' #WARNING (Thread-24) [pychromecast.socket_client] [Living Room Speaker(192.168.1.198):8009] Heartbeat timeout, resetting connection
    - 'Failed to connect to service' #ERROR (Thread-22) [pychromecast.socket_client] [Broadcast Speakers([::ffff:c0a8:1c3]):32169] Failed to connect to service ServiceInfo(type='host', data=('[::ffff:c0a8:1c3]', 32169)), retrying in 5.0s
    - 'Error reading from socket' #ERROR (Thread-22) [pychromecast.socket_client] [Broadcast Speakers(192.168.1.194):32169] Error reading from socket.
    - 'Error communicating with socket' #WARNING (Thread-22) [pychromecast.socket_client] [Broadcast Speakers(192.168.1.194):32169] Error communicating with socket, resetting connection

  homeassistant.components.mold_indicator.sensor:
    - 'Unable to parse' #ERROR (MainThread) [homeassistant.components.mold_indicator.sensor] Unable to parse temperature sensor sensor.outdoor_temperature with state: unavailable

  homeassistant.components.input_select:
    - 'no longer valid' #WARNING (MainThread) [homeassistant.components.input_select] Current option: none no longer valid (possible options: Oldies but Goldies, Classic Oldies, All About Country,

  homeassistant.components.sensor:
    - 'took longer than the scheduled update interval' #WARNING (MainThread) [homeassistant.components.sensor] Updating breaking_changes sensor took longer than the scheduled update interval 0:00:05
    - 'Setup of sensor' #WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform darksky is taking over 10 seconds.
    - 'waqi: Error on device update!' #ERROR (MainThread) [homeassistant.components.sensor] waqi: Error on device update!
    - 'Retrying in background in' #WARNING (MainThread) [homeassistant.components.sensor] Platform waqi not ready yet; Retrying in background in 30 seconds

  homeassistant.components.media_player:
    - 'Setup of' #WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform roku is taking over 10 seconds.
    - 'took longer than the scheduled update interval' #WARNING (MainThread) [homeassistant.components.media_player] Updating webostv media_player took longer than the scheduled update interval 0:00:10

  homeassistant.components.binary_sensor:
    - 'Setup of' #WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform pi_hole is taking over 10 seconds.
    - 'took longer than the scheduled update interval' #WARNING (MainThread) [homeassistant.components.binary_sensor] Updating hydrawise binary_sensor took longer than the scheduled update interval 0:00:30

  homeassistant.setup:
    - 'is taking over 10 seconds' #WARNING (MainThread) [homeassistant.setup] Setup of group is taking over 10 seconds.

  homeassistant.components.weather:
    - 'is taking over 10 seconds' #WARNING (MainThread) [homeassistant.components.weather] Setup of weather platform template is taking over 10 seconds.
    - 'took longer than the scheduled update' #WARNING (MainThread) [homeassistant.components.weather] Updating weatherflow weather took longer than the scheduled update interval 0:00:30

  homeassistant.components.light:
    - 'is taking over 10 seconds' #WARNING (MainThread) [homeassistant.components.light] Setup of light platform virtual is taking over 10 seconds.
    - 'took longer than the scheduled update interval' #WARNING (MainThread) [homeassistant.components.light] Updating virtual light took longer than the scheduled update interval 0:00:30

  homeassistant.components.fan:
    - 'is taking over 10 seconds' #WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform template is taking over 10 seconds.

  homeassistant.components.switch:
    - 'is taking over 10 seconds' #WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform template is taking over 10 seconds.
    - 'took longer than the scheduled update interval' #WARNING (MainThread) [homeassistant.components.switch] Updating hydrawise switch took longer than the scheduled update interval 0:00:30

  homeassistant.components.geo_location:
    - 'is taking over 10 seconds' #WARNING (MainThread) [homeassistant.components.geo_location] Setup of geo_location platform gdacs is taking over 10 seconds.

  homeassistant.config_entries:
    - 'integration not ready yet' #WARNING (MainThread) [homeassistant.config_entries] Config entry 'Home' for accuweather integration not ready yet; Retrying in background

  homeassistant.components.updater:
    - 'Timeout fetching Home Assistant update data' #ERROR (MainThread) [homeassistant.components.updater] Timeout fetching Home Assistant update data
    - 'Error requesting Home Assistant update data' #ERROR (MainThread) [homeassistant.components.updater] Error requesting Home Assistant update data: [Errno 32] Broken pipe

  homeassistant.components.calendar:
    - 'is taking over 10 seconds' #WARNING (MainThread) [homeassistant.components.calendar] Setup of calendar platform google is taking over 10 seconds.
    - 'is taking longer than 60 seconds' #ERROR (MainThread) [homeassistant.components.calendar] Setup of platform google is taking longer than 60 seconds. Startup will proceed without waiting any longer.
    - 'took longer than the scheduled update interval' #WARNING (MainThread) [homeassistant.components.calendar] Updating google calendar took longer than the scheduled update interval 0:01:00

  homeassistant.components.camera:
    - 'is taking over 10 seconds' #WARNING (MainThread) [homeassistant.components.camera] Setup of camera platform generic is taking over 10 seconds.

  homeassistant.components.scene:
    - 'is taking over 10 seconds' #WARNING (MainThread) [homeassistant.components.scene] Setup of scene platform homeassistant is taking over 10 seconds.

  aio_georss_client.feed:
    - 'failed with timeout error' #Requesting data from https://www.gdacs.org/xml/rss.xml failed with timeout error

  aio_georss_client.feed_manager:
    - 'Update not successful' #WARNING (MainThread) [aio_georss_client.feed_manager] Update not successful, no data received from <GdacsFeed(home=(42.30427713978584, -82.92516946792604), url=https://www.gdacs.org/xml/rss.xml, radius=10000, categories=[])>

  homeassistant.components.hassio.handler:
    - 'Timeout on' #ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/core_zwave_js/info request

  homeassistant.components.zwave_js:
    - 'Failed to get the Z-Wave JS add-on info' #ERROR (MainThread) [homeassistant.components.zwave_js] Failed to get the Z-Wave JS add-on info:
    - 'Failed to connect' #ERROR (MainThread) [homeassistant.components.zwave_js] Failed to connect:

  homeassistant.components.asuswrt.router:
    - 'Unexpected error fetching sensors_bytes data' #ERROR (MainThread) [homeassistant.components.asuswrt.router] Unexpected error fetching sensors_bytes data: list index out of range
    - 'Unexpected error fetching sensors_load_avg data' #ERROR (MainThread) [homeassistant.components.asuswrt.router] Unexpected error fetching sensors_load_avg data: list index out of range
    - 'Unexpected error fetching sensors_rates data' #ERROR (MainThread) [homeassistant.components.asuswrt.router] Unexpected error fetching sensors_rates data: list index out of range
    - 'Unexpected error fetching sensors_temperatures data' #ERROR (MainThread) [homeassistant.components.asuswrt.router] Unexpected error fetching sensors_temperatures data: list index out of range

  aioasuswrt.connection:
    - 'Host timeout' #ERROR (MainThread) [aioasuswrt.connection] Host timeout.

  homeassistant.components.roku.coordinator:
    - 'Error fetching roku data' #ERROR (MainThread) [homeassistant.components.roku.coordinator] Error fetching roku data: Invalid response from API: Timeout occurred while connecting to device

  homeassistant.components.waqi.sensor:
    - 'Failed to connect to WAQI servers' #ERROR (MainThread) [homeassistant.components.waqi.sensor] Failed to connect to WAQI servers

  homeassistant.components.environment_canada:
    - 'Unable to retrieve Environment Canada' #WARNING (MainThread) [homeassistant.components.environment_canada] Unable to retrieve Environment Canada weather

  homeassistant.components.zwave_js.entity: # manual zwave entity polling
    - 'Refreshing primary value' #INFO (MainThread) [homeassistant.components.zwave_js.entity] Refreshing primary value Value(value_id='161-37-0-currentValue') for switch.fireplace, state update may be delayed for devices on battery

  homeassistant.components.automation.zwave_poll_fireplace_switch: # manual zwave entity polling
    - 'Running automation actions' #INFO (MainThread) [homeassistant.components.automation.zwave_poll_fireplace_switch] [Zwave] Poll Fireplace Switch: Running automation actions
    - 'Executing step call service' #INFO (MainThread) [homeassistant.components.automation.zwave_poll_fireplace_switch] [Zwave] Poll Fireplace Switch: Executing step call service

  homeassistant.components.automation.spotify_spotify_hassio_update:
    - 'Restarting' #INFO (MainThread) [homeassistant.components.automation.spotify_spotify_hassio_update] [Spotify] Spotify Hassio Update: Restarting
    - 'Running automation actions'
    - 'Executing step call service'

  custom_components.frigate.api:
    - 'Timeout error fetching information' #ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate:5000/api/stats:
    - 'Error fetching information' #ERROR (MainThread) [custom_components.frigate.api] Error fetching information from http://ccab4aaf-frigate:5000/api/stats: Cannot connect to host ccab4aaf-frigate:5000 ssl:default [Try again]

  custom_components.frigate:
    - 'Error fetching frigate data' #ERROR (MainThread) [custom_components.frigate] Error fetching frigate data:

  aiohttp.server:
    - 'Error handling request' #ERROR (MainThread) [aiohttp.server] Error handling request

  matplotlib.font_manager:
    - 'Matplotlib is building the font cache' #WARNING (Thread-49) [matplotlib.font_manager] Matplotlib is building the font cache; this may take a moment.

  homeassistant.components.uptimerobot:
    - 'Error fetching uptimerobot data' #ERROR (MainThread) [homeassistant.components.uptimerobot] Error fetching uptimerobot data: Request timeout for 'https://api.uptimerobot.com/v2/getMonitors'

  hass_nabucasa.google_report_state:
    - 'Unable to connect' #WARNING (MainThread) [hass_nabucasa.google_report_state] Unable to connect: 503, message='Invalid response status', url=URL('wss://remotestate.nabucasa.com/v1')

  homeassistant.components.button:
    - 'is taking over 10 seconds' #WARNING (MainThread) [homeassistant.components.button] Setup of button platform mqtt is taking over 10 seconds.
    - 'is taking longer than 60 seconds' #ERROR (MainThread) [homeassistant.components.button] Setup of platform mqtt is taking longer than 60 seconds. Startup will proceed without waiting any longer.

  aioshelly.block_device:
    - 'device 192.168.1.140 initialize error - TimeoutError()' #WARNING (MainThread) [aioshelly.block_device] device 192.168.1.140 initialize error - TimeoutError()
    - 'device 192.168.1.141 initialize error - TimeoutError()' #WARNING (MainThread) [aioshelly.block_device] device 192.168.1.141 initialize error - TimeoutError()
    - 'device 192.168.1.142 initialize error - TimeoutError()' #WARNING (MainThread) [aioshelly.block_device] device 192.168.1.142 initialize error - TimeoutError()
    - 'device 192.168.1.143 initialize error - TimeoutError()' #WARNING (MainThread) [aioshelly.block_device] device 192.168.1.143 initialize error - TimeoutError()
    - 'device 192.168.1.144 initialize error - TimeoutError()' #WARNING (MainThread) [aioshelly.block_device] device 192.168.1.144 initialize error - TimeoutError()

  homeassistant.helpers.event:
    - 'Error while processing state change for sensor.hub_hb_00073766_weather' #ERROR (MainThread) [homeassistant.helpers.event] Error while processing state change for sensor.hub_hb_00073766_weather
    - 'Error while processing state change for sensor.tempest_st_00057689_temperature' #ERROR (MainThread) [homeassistant.helpers.event] Error while processing state change for sensor.tempest_st_00057689_temperature

  homeassistant.components.climate:
    - 'is taking over 10 seconds' #WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform smartthinq_sensors is taking over 10 seconds.

  haffmpeg.tools:
    - 'Timeout reading image' #WARNING (MainThread) [haffmpeg.tools] Timeout reading image

  homeassistant.components.cast.media_player:
    - 'Failed to cast media https://www.home-assistant.io/images/cast/splash.png' #ERROR (Thread-13) [homeassistant.components.cast.media_player] Failed to cast media https://www.home-assistant.io/images/cast/splash.png. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address

  homeassistant.components.systemmonitor.sensor:
    - 'took longer than the scheduled update interval' #WARNING (MainThread) [homeassistant.components.systemmonitor.sensor] Updating systemmonitor took longer than the scheduled update interval 0:00:15

  homeassistant.components.mobile_app.notify:
    - 'Timeout sending notification' #ERROR (MainThread) [homeassistant.components.mobile_app.notify] Timeout sending notification to https://mobile-apps.home-assistant.io/api/sendPush/android/v1

  homeassistant.components.alarm_control_panel:
    - 'is taking over 10 seconds' #WARNING (MainThread) [homeassistant.components.alarm_control_panel] Setup of alarm_control_panel platform alarmo is taking over 10 seconds.

  homeassistant.components.device_tracker:
    - 'is taking over 10 seconds' #WARNING (MainThread) [homeassistant.components.device_tracker] Setup of device_tracker platform mobile_app is taking over 10 seconds.

  hass_nabucasa.cloud_api:
    - 'Fetched https://remotestate.nabucasa.com/request_sync' #WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://remotestate.nabucasa.com/request_sync (500)

  homeassistant.components.number:
    - 'is taking over 10 seconds' #WARNING (MainThread) [homeassistant.components.number] Setup of number platform google_home is taking over 10 seconds.

  pyopenuv.client:
    - 'Giving up _async_request' #ERROR (MainThread) [pyopenuv.client] Giving up _async_request(...) after 1 tries (aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://api.openuv.io/api/v1/protection?from=3.5&to=3.5&lat=42.304285&lng=-82.9256952&alt=190.0'))

  homeassistant.components.openuv:
    - 'Config entry failed' #ERROR (MainThread) [homeassistant.components.openuv] Config entry failed: Error during protection data update: 500, message='Internal Server Error', url=URL('https://api.openuv.io/api/v1/protection?from=3.5&to=3.5&lat=42.304285&lng=-82.9256952&alt=190.0')
